In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline 

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## Import Dataset

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Capstone/Dataset/DATA FINAL DA_ED19.csv", sep=';')
df.head()

kode univ         Nama Universitas  kode prodi               nama prodi  \
0        111  UNIVERSITAS SYIAH KUALA     1111014  PENDIDIKAN DOKTER HEWAN   
1        111  UNIVERSITAS SYIAH KUALA     1111022             TEKNIK SIPIL   
2        111  UNIVERSITAS SYIAH KUALA     1111037             TEKNIK MESIN   
3        111  UNIVERSITAS SYIAH KUALA     1111045             TEKNIK KIMIA   
4        111  UNIVERSITAS SYIAH KUALA     1111053               ARSITEKTUR   

  jenjang    jenis  Daya Tampung 2022 jenis portofolio  Tahun Provinsi  \
0      S1  SAINTEK                 99        Tidak Ada   2017     Aceh   
1      S1  SAINTEK                 81        Tidak Ada   2017     Aceh   
2      S1  SAINTEK                 63        Tidak Ada   2017     Aceh   
3      S1  SAINTEK                 63        Tidak Ada   2017     Aceh   
4      S1  SAINTEK                 63        Tidak Ada   2017     Aceh   

   Peminat  Daya Tampung  
0      364            88  
1     1556            64  
2      556            48  
3      251            48  
4      725            48

In [ ]:
df.describe()

kode univ    kode prodi  Daya Tampung 2022          Tahun  \
count  536690.000000  5.366900e+05      536690.000000  536690.000000   
mean      421.504276  4.216655e+06          55.283180    2019.000000   
std       223.975213  2.239748e+06          39.850466       1.414215   
min       111.000000  1.111014e+06           6.000000    2017.000000   
25%       321.000000  3.211166e+06          32.000000    2018.000000   
50%       362.000000  3.622257e+06          48.000000    2019.000000   
75%       612.000000  6.121167e+06          66.000000    2020.000000   
max       921.000000  9.212073e+06         582.000000    2021.000000   

             Peminat   Daya Tampung  
count  536690.000000  536690.000000  
mean       16.806382      52.880710  
std       101.560515      37.948984  
min         0.000000       0.000000  
25%         0.000000      31.000000  
50%         0.000000      44.000000  
75%         2.000000      64.000000  
max      3791.000000     528.000000

## Kapitalisasi Data Frame

In [ ]:
df['nama prodi'].str.isupper().unique()

array([ True, False])

Karena Terdapat variabel yang belum terkapitalisasi maka dilakukan kapitalisasi terlebih dahulu

In [ ]:
df['nama prodi']= df['nama prodi'].str.upper()

Lalu kita cek terlebih dahulu apakah semua sudah terkapitalisasi dengan baik atau belum

In [ ]:
df['nama prodi'].str.isupper().unique()
# Didapati tidak ada masalah kapitalisasi pada data

array([ True])

## Membenahi masalah duplikasi 

In [ ]:
a='TEKNIK MESIN'
df['nama prodi'][df['nama prodi'].str.contains(a)].unique()

array(['TEKNIK MESIN', 'PENDIDIKAN VOKASIONAL TEKNIK MESIN',
       'PENDIDIKAN TEKNIK MESIN', 'TEKNIK MESIN (NK)',
       'PEND TEKNIK MESIN', 'FAKULTAS TEKNIK MESIN & DIRGANTARA (FTMD)',
       'PEND. TEKNIK MESIN'], dtype=object)

In [ ]:
a='TEKNIK MESIN'
b='Teknik Mesin'

df.loc[df['nama prodi'].str.contains(a), 'nama prodi']= b
df['nama prodi'][df['nama prodi'].str.contains(b)].unique()

array(['Teknik Mesin'], dtype=object)

In [ ]:
a='KEDOKTERAN'
df['nama prodi'][df['nama prodi'].str.contains(a)].unique()

array(['KEDOKTERAN', 'KEDOKTERAN GIGI', 'PEND. KEDOKTERAN',
       'KEDOKTERAN HEWAN', 'KEDOKTERAN HEWAN (SIKIA BANYUWANGI)'],
      dtype=object)

In [ ]:
a='KEDOKTERAN HEWAN'
b='Kedokteran Hewan'

df.loc[df['nama prodi'].str.contains(a), 'nama prodi']= b
df['nama prodi'][df['nama prodi'].str.contains(b)].unique()

array(['Kedokteran Hewan'], dtype=object)

In [ ]:
a='DOKTER HEWAN'
b='Kedokteran Hewan'

df.loc[df['nama prodi'].str.contains(a), 'nama prodi']= b
df['nama prodi'][df['nama prodi'].str.contains(b)].unique()

array(['Kedokteran Hewan'], dtype=object)

In [ ]:
a='KEDOKTERAN GIGI'
b='Kedokteran Gigi'

df.loc[df['nama prodi'].str.contains(a), 'nama prodi']= b
df['nama prodi'][df['nama prodi'].str.contains(b)].unique()

array(['Kedokteran Gigi'], dtype=object)

In [ ]:
a='KEDOKTERAN'
b='Kedokteran'

df.loc[df['nama prodi'].str.contains(a), 'nama prodi']= b
df['nama prodi'][df['nama prodi'].str.contains(b)].unique()

array(['Kedokteran', 'Kedokteran Gigi', 'Kedokteran Hewan'], dtype=object)

In [ ]:
a='PSIKOLOGI'
df['nama prodi'][df['nama prodi'].str.contains(a)].unique()

array(['PSIKOLOGI', 'ILMU PSIKOLOGI',
       'PSIKOLOGI PENDIDIKAN DAN BIMBINGAN'], dtype=object)

In [ ]:
a='PSIKOLGOI'
b='Psikologi'

df.loc[df['nama prodi'].str.contains(a), 'nama prodi']= b
df['nama prodi'][df['nama prodi'].str.contains(b)].unique()

array([], dtype=object)

In [ ]:
a='HUKUM'
df['nama prodi'][df['nama prodi'].str.contains(a)].unique()
#ADA HUKUM SYARIAH, DIBENERIN!!!!

array(['ILMU HUKUM', 'HUKUM', 'ILMU HUKUM (IH)', 'HUKUM BISNIS SYARIAH',
       'HUKUM ADMINISTRASI NEGARA', 'IL. HUKUM',
       'ILMU HUKUM (PSDKU KAB. MBD)', 'ILMU HUKUM (PSDKU KAB. ARU)'],
      dtype=object)

In [ ]:
a='HUKUM BISNIS SYARIAH'
b='Ilmu Hukum'

df.loc[df['nama prodi'].str.contains(a), 'nama prodi']= b
df['nama prodi'][df['nama prodi'].str.contains(b)].unique()

In [ ]:
a='HUKUM'
b='Ilmu Hukum'

df.loc[df['nama prodi'].str.contains(a), 'nama prodi']= b
df['nama prodi'][df['nama prodi'].str.contains(b)].unique()

array(['Ilmu Hukum'], dtype=object)

In [ ]:
a='MANAJEMEN'

list(df['nama prodi'][df['nama prodi'].str.contains(a)].unique())

['MANAJEMEN SUMBER DAYA PERAIRAN',
 'MANAJEMEN SUMBERDAYA PERAIRAN',
 'MANAJEMEN HUTAN',
 'TEKNOLOGI & MANAJEMEN PERIKANAN BUDIDAYA',
 'MANAJEMEN',
 'MANAJEMEN SUMBERDAYA LAHAN',
 'TEKNOLOGI & MANAJEMEN PERIKANAN TANGKAP',
 'MANAJEMEN SUMBERDAYA AKUATIK (MANAJEMEN SUMBER DAYA PERIKANAN)',
 'MANAJEMEN SD PERAIRAN',
 'MANAJEMEN (PSDKU GAYO LUES)',
 'EKONOMI MANAJEMEN',
 'MANAJEMEN (KAMPUS 2 PAYAKUMBUH)',
 'MANAJEMEN (NK)',
 'MANAJEMEN PERHOTELAN (NK)',
 'MANAJEMEN PENDIDIKAN',
 'SEKOLAH BISNIS DAN MANAJEMEN (SBM)',
 'MANAJEMEN KOMUNIKASI',
 'MANAJEMEN RESORT DAN LEISURE',
 'MANAJEMEN PEMASARAN PARIWISATA',
 'MANAJEMEN INDUSTRI KATERING',
 'PENDIDIKAN MANAJEMEN PERKANTORAN',
 'MANAJEMEN DAN KEBIJAKAN PUBLIK',
 'MANAJEMEN BISNIS',
 'MANAJEMEN  (KELAS INTERNASIONAL)',
 'MANAJEMEN S1',
 'MANAJEMEN (PSDKU MOROWALI)',
 'MANAJEMEN (PSDKU TOUNA)',
 'MANAJEMEN ADMINISTRASI PERKANTORAN']

GABISA FILTER BERDASARKAN KATA PERTAMA DAN TERAKHIR :")


In [ ]:
a= 'ADMINISTRASI BISNIS'
list(df['nama prodi'][df['nama prodi'].str.contains(a)].unique())

['ADMINISTRASI BISNIS',
 'ILMU ADMINISTRASI BISNIS',
 'ADMINISTRASI BISNIS PSDKU PANGANDARAN']

In [ ]:
a='ADMINISTRASI BISNIS'
b='Administrasi Bisnis'

df.loc[df['nama prodi'].str.contains(a),'nama prodi']=b
df['nama prodi'][df['nama prodi'].str.contains(b)].unique()

array(['Administrasi Bisnis'], dtype=object)

In [ ]:
a= 'ILMU KOMUNIKASI'
list(df['nama prodi'][df['nama prodi'].str.contains(a)].unique())

['ILMU KOMUNIKASI', 'ILMU KOMUNIKASI PSDKU PANGANDARAN']

In [ ]:
a='ILMU KOMUNIKASI'
b='Ilmu Komunikasi'
df.loc[df['nama prodi'].str.contains(a),'nama prodi']=b
df['nama prodi'][df['nama prodi'].str.contains(b)].unique()

array(['Ilmu Komunikasi'], dtype=object)

In [ ]:
a='AGROTEKNOLOGI'
list(df['nama prodi'][df['nama prodi'].str.contains(a)].unique())

['AGROTEKNOLOGI',
 'AGROTEKNOLOGI (PSDKU GAYO LUES)',
 'AGROTEKNOLOGI / AGROEKOTEKNOLOGI',
 'AGROTEKNOLOGI (PSDKU MOROWALI)',
 'AGROTEKNOLOGI (PSDKU TOUNA)']

In [ ]:
a='AGROTEKNOLOGI'
b='Agroteknologi'

df.loc[df['nama prodi'].str.contains(a), 'nama prodi']=b
df['nama prodi'][df['nama prodi'].str.contains(b)].unique()

array(['Agroteknologi'], dtype=object)

In [ ]:
a='PETERNAKAN'
list(df['nama prodi'][df['nama prodi'].str.contains(a)].unique())

['PETERNAKAN',
 'PETERNAKAN ( KAMPUS II PAYAKUMBUH)',
 'ILMU PETERNAKAN',
 'PETERNAKAN PSDKU PANGANDARAN',
 'ILMU DAN INDUSTRI PETERNAKAN',
 'PETERNAKAN (PSDKU KEDIRI)',
 'PETERNAKAN (PSDKU KAB. MBD)']

In [ ]:
a= 'PETERNAKAN'
b='Peternakan'

df.loc[df['nama prodi'].str.contains(a)]=b
df['nama prodi'][df['nama prodi'].str.contains(b)].unique()

array(['Peternakan'], dtype=object)

In [ ]:
a='AKUAKULTUR'
list(df['nama prodi'][df['nama prodi'].str.contains(a)].unique())

['AKUAKULTUR',
 'AKUAKULTUR (BUDIDAYA PERIKANAN)',
 'AKUAKULTUR (PSDKU KEDIRI)',
 'AKUAKULTUR (SIKIA BANYUWANGI)']

In [ ]:
a='AKUAKULTUR'
b='Akuakultur'
df.loc[df['nama prodi'].str.contains(a)]=b
df['nama prodi'][df['nama prodi'].str.contains(b)].unique()

array(['Akuakultur'], dtype=object)

In [ ]:
a='SIPIL'
df['nama prodi'][df['nama prodi'].str.contains(a)].unique()

array(['TEKNIK SIPIL',
       'FAKULTAS TEKNIK SIPIL & LINGKUNGAN (FTSL)  0 KAMPUS GANESA',
       'FAKULTAS TEKNIK SIPIL DAN LINGKUNGAN (FTSL) 0 KAMPUS JATINANGOR',
       'TEKNIK SIPIL DAN LINGKUNGAN',
       'PENDIDIKAN TEKNIK SIPIL & PERENCANAAN',
       'TEKNIK SIPIL (PSDKU MOROWALI)', 'TEKNIK SIPIL (PSDKU TOUNA)'],
      dtype=object)

In [ ]:
a='SIPIL'
b='Teknik Sipil'

df.loc[df['nama prodi'].str.contains(a)]=b
df['nama prodi'][df['nama prodi'].str.contains(b)].unique()

array(['Teknik Sipil'], dtype=object)

In [ ]:
a='TEKNIK ELEKTRO'

list(df['nama prodi'][df['nama prodi'].str.contains(a)].unique())

['TEKNIK ELEKTRO',
 'PENDIDIKAN TEKNIK ELEKTRO',
 'PENDIDIKAN TEKNIK ELEKTRONIKA',
 'TEKNIK ELEKTRO INDUSTRI (NK)',
 'PENDIDIKAN VOKASIONAL TEKNIK ELEKTRO',
 'PENDIDIKAN VOKASIONAL TEKNIK ELEKTRONIKA',
 'PEND. TEKNIK ELEKTRO',
 'PEND. TEKNIK ELEKTRONIKA']

In [ ]:
a='TEKNIK ELEKTRO'
b='Teknik Elektro'

df.loc[df['nama prodi'].str.contains(a)]=b
df['nama prodi'][df['nama prodi'].str.contains(b)].unique()

array(['Teknik Elektro'], dtype=object)

In [ ]:
a='TEKNIK INFORMATIKA'
df['nama prodi'][df['nama prodi'].str.contains(a)].unique()

array(['TEKNIK INFORMATIKA', 'PEND. TEKNIK INFORMATIKA DAN KOMPUTER',
       'PENDIDIKAN TEKNIK INFORMATIKA & KOMPUTER',
       'PEND. TEKNIK INFORMATIKA & KOMPUTER',
       'PENDIDIKAN TEKNIK INFORMATIKA'], dtype=object)

In [ ]:
a='TEKNIK INFORMATIKA'
b='Teknik Informatika'
df.loc[df['nama prodi'].str.contains(a)]=b
df['nama prodi'][df['nama prodi'].str.contains(b)].unique()

array(['Teknik Informatika'], dtype=object)

In [ ]:
a='INFORMATIKA'
b='Teknik Informatika'
df.loc[df['nama prodi'].str.contains(a)]=b
df['nama prodi'][df['nama prodi'].str.contains(b)].unique()

array(['Teknik Informatika'], dtype=object)

In [ ]:
a='ARSITEKTUR'
df['nama prodi'][df['nama prodi'].str.contains(a)].unique()

array(['ARSITEKTUR', 'TEKNIK ARSITEKTUR', 'ARSITEKTUR LANSKAP',
       'ARSITEKTUR INTERIOR',
       'SEK. ARSITEKTUR, PERENC & PENGEMB KEBIJAKAN',
       'SEK. ARSITEKTUR, PERENC & PENGEMB KEBIJAKAN (SAPPK) 0 KAMPUS CIREBON',
       'PENDIDIKAN TEKNIK ARSITEKTUR', 'ARSITEKTUR LANSEKAP'],
      dtype=object)

In [ ]:
a='ARSITEKTUR'
b='Arsitektur'
df.loc[df['nama prodi'].str.contains(a)]=b
df['nama prodi'][df['nama prodi'].str.contains(b)].unique()


array(['Arsitektur'], dtype=object)

## Mengembalikan Kapitalisasi Dataset

In [ ]:
df['nama prodi'].str.isupper().unique()

array([ True])

In [ ]:
df['nama prodi']=df['nama prodi'].str.upper()

In [ ]:
df['nama prodi'].str.isupper().unique()

array([ True])

In [ ]:
a='TEKNIK'

list(df['nama prodi'][df['nama prodi'].str.contains(a)].unique())

['TEKNIK KIMIA',
 'TEKNIK PERTANIAN',
 'TEKNIK INDUSTRI',
 'TEKNIK GEOFISIKA',
 'TEKNIK PERTAMBANGAN',
 'TEKNIK GEOLOGI',
 'TEKNIK KOMPUTER',
 'TEKNIK MATERIAL',
 'TEKNIK LINGKUNGAN',
 'KETEKNIKAN PERTANIAN',
 'PENDIDIKAN TEKNIK BANGUNAN',
 'PENDIDIKAN TEKNIK OTOMOTIF',
 'TEKNIK ARSITEK',
 'TEKNIK PERTANIAN DAN BIOSISTEM',
 'TEKNIK PERTAMBANGAN (NK)',
 'TEKNIK GEODESI',
 'TEKNIK GEOMATIKA',
 'TEKNIK FISIKA',
 'TEKNIK KELAUTAN',
 'TEKNIK BIOSISTEM',
 'TEKNIK SISTEM ENERGI',
 'TEKNIK METALURGI',
 'TEKNIK METALURGI & MATERIAL',
 'TEKNIK PERKAPALAN',
 'TEKNIK BIOMEDIS',
 'FAK. TEKNIK PERTAMB. & PERMINYAKAN (FTTM)',
 'TEKNIK NUKLIR',
 'PENDIDIKAN TEKNIK MEKATRONIKA',
 'TEKNIK MANUFAKTUR',
 'TEKNIK PERMINYAKAN',
 'TEKNIK KONSTRUKSI PERKAPALAN',
 'TEKNIK PENGAIRAN',
 'TEKNIK INDUSTRI PERTANIAN',
 'TEKNIK SISTEM PERKAPALAN',
 'TEKNIK TRANSPORTASI LAUT',
 'TEKNIK BIOMEDIK',
 'PEND. TEKNIK BANGUNAN',
 'TEKNIK MEKATRONIKA',
 'TEKNIK MATERIAL DAN METALURGI',
 'TEKNIK PENGEMB. WILAYAH KOTA',
 'PEND